- name: Crear directorio del proyecto
  file:
    path: "{{ project_path }}"
    state: directory

- name: Configurar config.yaml
  template:
    src: config.yaml.j2
    dest: "{{ project_path }}/config.yaml"

- name: Configurar docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_path }}/docker-compose.yml"

- name: Levantar contenedores con Podman
  command: podman-compose -d up
  args:
    chdir: "{{ project_path }}"
