- name: Crear directorio del proyecto
  file:
    path: "{{ project_path }}"
    state: directory

- name: Clonar repositorio del toolkit
  git:
    repo: https://github.com/HackCTF/toolkit-installation.git
    dest: "{{ project_path }}/toolkit-installation"
    version: main  # Cambia si el branch es diferente

- name: Copiar config.yaml desde el repositorio
  copy:
    src: "{{ project_path }}/toolkit-installation/quay/config.yaml"
    dest: "{{ project_path }}/config.yaml"


- name: Configurar docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_path }}/docker-compose.yml"

- name: Levantar contenedores con Podman
  command: podman-compose -d up
  args:
    chdir: "{{ project_path }}"
